### ISSUE TITLE
Internal profile tabs are not properly cleaned up

### ISSUE THREAD

**Issue by ModderK** [simplyWiri/Dubs-Performance-Analyzer#6]
Internal profile tabs are not properly cleaned up after allowing the analyzer to unpatch itself, causing issues if a user attempts to profile the same method again without restarting.

To reproduce:
1. Open the analyzer and internal profile the method.
2. Close the analyzer and wait for unpatching to complete.

After allowing unpatching to complete, opening the analyzer again and clicking the internal profile tab will cause a null reference exception. Additionally, trying to internal profile the method again will cause a duplicate type error.

**Comment by simplyWiri** [comment]
Should be fixed with the above commit. Let me know if there are still issues, If not I'll close within 24h

**Comment by ModderK** [comment]
Looks to be fixed with the above commit.
