### ISSUE TITLE
Window sizing with side tab enabled

### ISSUE THREAD

**Issue by ModderK** [simplyWiri/Dubs-Performance-Analyzer#7]
The default analyzer window size does not adjust with the side tab enabled, causing the window to reset to its default size when closed and reopened. This is a minor annoyance, but it would be nice if the analyzer remembered the previous size when it was opened again after closing.

**Comment by simplyWiri** [comment]
Should be a feature in the above commit.

Open to discussion for how this should work in conjunction with the bottom tab.

**Comment by ModderK** [comment]
This issue resolved in the latest version.
